Feature/first
itk-dev-rpa/folkeregister-udrejse pull request #1
Opened 2024-05-28 08:02 UTC by ghbm-itk

2024-05-28 12:18 UTC, bakspace-itk requested changes

2024-05-28 12:18 UTC, bakspace-itk commented on robot_framework/process.py
> +            smtp_util.send_email(sender_email, "itk-rpa@mkb.aarhus.dk", "Anmodning afvist", "Din anmodning til Udrejsekontrol er blevet afvist, da du ikke er på listen af godkendt medarbejdere.", smt
Der mangler et bogstav
```suggestion
            smtp_util.send_email(sender_email, "itk-rpa@mkb.aarhus.dk", "Anmodning afvist", "Din anmodning til Udrejsekontrol er blevet afvist, da du ikke er på listen af godkendte medarbejdere.", smtp_server=config.SMTP_SERVER, smtp_port=config.SMTP_PORT)
```

2024-05-28 12:18 UTC, bakspace-itk commented on robot_framework/reset.py
> +    cred = orchestrator_connection.get_credential(config.INDKOMST_CREDS)
Det er lidt forvirrende at cred kan være enten credentials eller credits, når det peger ind i noget med indkomst, men måske er det bare min gamerhjerne

2024-05-28 12:29 UTC, ghbm-itk commented on robot_framework/reset.py
> +    cred = orchestrator_connection.get_credential(config.INDKOMST_CREDS)
I DISAGREE!

2024-05-29 07:52 UTC, rimi-itk approved these changes
Approved with some suggestions on fixing typos.

2024-05-29 07:52 UTC, rimi-itk commented on README.md
> +The robot expects a list of approved case workers as input. This is given as a JSON string:
```suggestion
The robot expects a list of approved case workers as input. This is given as a JSON object:
```

2024-05-29 07:52 UTC, rimi-itk commented on migration.py
> +        AND first_name is not NULL"""
```suggestion
        WHERE created_date IS NOT NULL
        AND first_name IS NOT NULL"""
```

2024-05-29 07:52 UTC, rimi-itk commented on robot_framework/process.py
> +            smtp_util.send_email(sender_email, "itk-rpa@mkb.aarhus.dk", "Udrejse sager oprettet", f"Din anmodning til Udrejsekontrol er blevet behandlet.\nDer er blevet gennemsøgt {handled_count} per
```suggestion
            smtp_util.send_email(sender_email, "itk-rpa@mkb.aarhus.dk", "Udrejsesager oprettet", f"Din anmodning til Udrejsekontrol er blevet behandlet.\nDer er blevet gennemsøgt {handled_count} personer og oprettet {found_count} nye sager i KMD Nova.", smtp_server=config.SMTP_SERVER, smtp_port=config.SMTP_PORT)
```

2024-05-31 07:37 UTC, bakspace-itk approved these changes
Det ser godt ud :)

2024-05-31 08:10 UTC, merged